-- Fresh-install prerequisite previously assumed by migration 0004.
-- Existing installations keep their table and data unchanged.
create table if not exists public.activity_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    username text,
    role text not null,
    action text not null,
    resource text,
    resource_id text,
    details jsonb,
    created_at timestamptz not null default now()
);
alter table public.activity_logs enable row level security;
revoke all on public.activity_logs from anon;
grant select on public.activity_logs to authenticated;
