-- ============================================================
-- LPMAS - SUPABASE DATABASE SETUP
-- Required tables for Raspberry Pi app.py
--
-- Tables:
--   1. sensor_minute_aggregates
--   2. monitoring_incidents
--   3. system_settings
--
-- Raw 10-second readings remain in Raspberry Pi SQLite.
-- Supabase stores cloud history/aggregates and incidents.
-- ============================================================


-- ============================================================
-- 0. EXTENSIONS
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- 1. SENSOR MINUTE AGGREGATES
-- ============================================================
-- Receives completed minute-level summaries from Raspberry Pi.
--
-- One row represents:
--   sensor + minute
--
-- Raw 10-second readings are NOT stored here.
-- ============================================================

create table if not exists public.sensor_minute_aggregates (
    id bigint generated by default as identity primary key,

    sensor_id text not null,
    greenhouse_id text not null,

    bucket_start timestamptz not null,
    phase_type text not null,

    sample_count integer not null default 0,

    avg_lux numeric(12,3) not null,
    min_lux numeric(12,3) not null,
    max_lux numeric(12,3) not null,

    safe_count integer not null default 0,
    warning_count integer not null default 0,
    violation_count integer not null default 0,

    updated_at timestamptz not null default now(),

    -- The Python backend currently uses:
    -- on_conflict="sensor_id,bucket_start"
    constraint sensor_minute_aggregates_sensor_bucket_unique
        unique (sensor_id, bucket_start),

    -- Data validation
    constraint sensor_minute_aggregates_phase_check
        check (phase_type in ('illumination', 'dark')),

    constraint sensor_minute_aggregates_sample_count_check
        check (sample_count >= 0),

    constraint sensor_minute_aggregates_safe_count_check
        check (safe_count >= 0),

    constraint sensor_minute_aggregates_warning_count_check
        check (warning_count >= 0),

    constraint sensor_minute_aggregates_violation_count_check
        check (violation_count >= 0),

    constraint sensor_minute_aggregates_lux_check
        check (
            avg_lux >= 0
            and min_lux >= 0
            and max_lux >= 0
            and min_lux <= max_lux
        )
);


-- Indexes for dashboard/history queries

create index if not exists idx_sensor_minute_aggregates_sensor
    on public.sensor_minute_aggregates (sensor_id);

create index if not exists idx_sensor_minute_aggregates_greenhouse
    on public.sensor_minute_aggregates (greenhouse_id);

create index if not exists idx_sensor_minute_aggregates_bucket
    on public.sensor_minute_aggregates (bucket_start desc);

create index if not exists idx_sensor_minute_aggregates_greenhouse_bucket
    on public.sensor_minute_aggregates (greenhouse_id, bucket_start desc);

create index if not exists idx_sensor_minute_aggregates_sensor_bucket
    on public.sensor_minute_aggregates (sensor_id, bucket_start desc);


-- ============================================================
-- 2. MONITORING INCIDENTS
-- ============================================================
-- Stores confirmed lighting violations generated by app.py.
--
-- Incident lifecycle:
--
--     open
--       ↓
--     acknowledged
--       ↓
--     resolved
--
-- A safe reading resolves an active incident.
-- ============================================================

create table if not exists public.monitoring_incidents (
    id bigint generated by default as identity primary key,

    -- ID of the incident generated by Raspberry Pi SQLite
    pi_incident_id bigint not null,

    sensor_id text not null,
    greenhouse_id text not null,

    phase_type text not null,

    opened_at timestamptz not null,
    resolved_at timestamptz,

    status text not null default 'open',

    peak_lux numeric(12,3) not null,
    lowest_lux numeric(12,3) not null,

    reason text not null,

    updated_at timestamptz not null default now(),

    -- Used by app.py:
    -- on_conflict="pi_incident_id"
    constraint monitoring_incidents_pi_id_unique
        unique (pi_incident_id),

    -- Valid incident statuses
    constraint monitoring_incidents_status_check
        check (status in ('open', 'acknowledged', 'resolved')),

    -- Valid phases
    constraint monitoring_incidents_phase_check
        check (phase_type in ('illumination', 'dark')),

    -- Lux values cannot be negative
    constraint monitoring_incidents_lux_check
        check (
            peak_lux >= 0
            and lowest_lux >= 0
        ),

    -- Peak must not be lower than lowest
    constraint monitoring_incidents_peak_low_check
        check (peak_lux >= lowest_lux),

    -- Resolved incidents must have a resolution time.
    -- Active incidents should not have one.
    constraint monitoring_incidents_resolution_check
        check (
            (status = 'resolved' and resolved_at is not null)
            or
            (status in ('open', 'acknowledged') and resolved_at is null)
        )
);


-- Indexes

create index if not exists idx_monitoring_incidents_sensor
    on public.monitoring_incidents (sensor_id);

create index if not exists idx_monitoring_incidents_greenhouse
    on public.monitoring_incidents (greenhouse_id);

create index if not exists idx_monitoring_incidents_status
    on public.monitoring_incidents (status);

create index if not exists idx_monitoring_incidents_opened
    on public.monitoring_incidents (opened_at desc);

create index if not exists idx_monitoring_incidents_greenhouse_status
    on public.monitoring_incidents (greenhouse_id, status);

create index if not exists idx_monitoring_incidents_sensor_status
    on public.monitoring_incidents (sensor_id, status);


-- ============================================================
-- 3. SYSTEM SETTINGS
-- ============================================================
-- Stores administrator/system configuration.
--
-- app.py specifically looks for:
--
--     key = 'manager_phone'
--
-- The Raspberry Pi uses the Supabase secret/service key to
-- retrieve this value.
--
-- IMPORTANT:
-- This table should NOT be publicly readable because it can
-- contain sensitive administrative configuration.
-- ============================================================

create table if not exists public.system_settings (
    id bigint generated by default as identity primary key,

    key text not null,
    value text,

    updated_at timestamptz not null default now(),

    constraint system_settings_key_unique
        unique (key),

    constraint system_settings_key_not_empty
        check (length(trim(key)) > 0)
);


-- Index for key lookups

create index if not exists idx_system_settings_key
    on public.system_settings (key);


-- ============================================================
-- 4. INSERT REQUIRED MANAGER PHONE SETTING
-- ============================================================
-- IMPORTANT:
-- Replace the placeholder phone number with the actual
-- manager number in Supabase.
--
-- Do NOT put the phone number directly into app.py.
--
-- You can also execute this separately later.
-- ============================================================

-- Example:
--
-- insert into public.system_settings (key, value)
-- values ('manager_phone', '09XXXXXXXXX')
-- on conflict (key)
-- do update set
--     value = excluded.value,
--     updated_at = now();


-- ============================================================
-- 5. ENABLE ROW LEVEL SECURITY
-- ============================================================

alter table public.sensor_minute_aggregates
    enable row level security;

alter table public.monitoring_incidents
    enable row level security;

alter table public.system_settings
    enable row level security;


-- ============================================================
-- 6. RLS POLICIES
-- ============================================================
--
-- SECURITY MODEL
--
-- Raspberry Pi app.py:
--     Uses SUPABASE_SECRET_KEY
--     → service-role/backend access
--     → bypasses normal RLS policies
--
-- Next.js/dashboard:
--     Uses normal Supabase client/auth
--     → authenticated users may READ dashboard/history data
--
-- Anonymous users:
--     Cannot read these tables.
--
-- system_settings:
--     Not readable by frontend users.
--     Only backend/service-role code should access it.
-- ============================================================


-- ------------------------------------------------------------
-- SENSOR MINUTE AGGREGATES
-- ------------------------------------------------------------

drop policy if exists "Authenticated users can view sensor aggregates"
    on public.sensor_minute_aggregates;

create policy "Authenticated users can view sensor aggregates"
on public.sensor_minute_aggregates
for select
to authenticated
using (true);


-- Explicitly prevent normal frontend users from inserting,
-- updating, or deleting cloud aggregates.
--
-- app.py uses the service-role/secret key, so its writes
-- continue to work without a frontend write policy.


drop policy if exists "Authenticated users cannot insert sensor aggregates"
    on public.sensor_minute_aggregates;

create policy "Authenticated users cannot insert sensor aggregates"
on public.sensor_minute_aggregates
for insert
to authenticated
with check (false);


drop policy if exists "Authenticated users cannot update sensor aggregates"
    on public.sensor_minute_aggregates;

create policy "Authenticated users cannot update sensor aggregates"
on public.sensor_minute_aggregates
for update
to authenticated
using (false)
with check (false);


drop policy if exists "Authenticated users cannot delete sensor aggregates"
    on public.sensor_minute_aggregates;

create policy "Authenticated users cannot delete sensor aggregates"
on public.sensor_minute_aggregates
for delete
to authenticated
using (false);


-- ------------------------------------------------------------
-- MONITORING INCIDENTS
-- ------------------------------------------------------------

drop policy if exists "Authenticated users can view monitoring incidents"
    on public.monitoring_incidents;

create policy "Authenticated users can view monitoring incidents"
on public.monitoring_incidents
for select
to authenticated
using (true);


-- Frontend cannot directly create incidents.
-- app.py is responsible for incident creation.

drop policy if exists "Authenticated users cannot insert monitoring incidents"
    on public.monitoring_incidents;

create policy "Authenticated users cannot insert monitoring incidents"
on public.monitoring_incidents
for insert
to authenticated
with check (false);


-- Frontend cannot directly modify incidents.
-- app.py controls incident lifecycle.

drop policy if exists "Authenticated users cannot update monitoring incidents"
    on public.monitoring_incidents;

create policy "Authenticated users cannot update monitoring incidents"
on public.monitoring_incidents
for update
to authenticated
using (false)
with check (false);


-- Frontend cannot delete historical incidents.

drop policy if exists "Authenticated users cannot delete monitoring incidents"
    on public.monitoring_incidents;

create policy "Authenticated users cannot delete monitoring incidents"
on public.monitoring_incidents
for delete
to authenticated
using (false);


-- ------------------------------------------------------------
-- SYSTEM SETTINGS
-- ------------------------------------------------------------
--
-- NO authenticated SELECT policy is intentionally created.
--
-- This prevents the Next.js frontend/normal users from
-- retrieving manager_phone and other administrative settings.
--
-- app.py uses the backend secret key and can still read it.
-- ------------------------------------------------------------

drop policy if exists "Authenticated users cannot view system settings"
    on public.system_settings;

create policy "Authenticated users cannot view system settings"
on public.system_settings
for select
to authenticated
using (false);


drop policy if exists "Authenticated users cannot insert system settings"
    on public.system_settings;

create policy "Authenticated users cannot insert system settings"
on public.system_settings
for insert
to authenticated
with check (false);


drop policy if exists "Authenticated users cannot update system settings"
    on public.system_settings;

create policy "Authenticated users cannot update system settings"
on public.system_settings
for update
to authenticated
using (false)
with check (false);


drop policy if exists "Authenticated users cannot delete system settings"
    on public.system_settings;

create policy "Authenticated users cannot delete system settings"
on public.system_settings
for delete
to authenticated
using (false);


-- ============================================================
-- 7. UPDATED_AT AUTOMATICALLY REFRESHES
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


drop trigger if exists trg_sensor_minute_aggregates_updated_at
    on public.sensor_minute_aggregates;

create trigger trg_sensor_minute_aggregates_updated_at
before update on public.sensor_minute_aggregates
for each row
execute function public.set_updated_at();


drop trigger if exists trg_monitoring_incidents_updated_at
    on public.monitoring_incidents;

create trigger trg_monitoring_incidents_updated_at
before update on public.monitoring_incidents
for each row
execute function public.set_updated_at();


drop trigger if exists trg_system_settings_updated_at
    on public.system_settings;

create trigger trg_system_settings_updated_at
before update on public.system_settings
for each row
execute function public.set_updated_at();


-- ============================================================
-- 8. OPTIONAL: INSERT MANAGER PHONE
-- ============================================================
-- Uncomment and replace the value when ready.
--
-- insert into public.system_settings (key, value)
-- values ('manager_phone', '09XXXXXXXXX')
-- on conflict (key)
-- do update set
--     value = excluded.value,
--     updated_at = now();


-- ============================================================
-- 9. VERIFICATION
-- ============================================================

select
    table_name
from information_schema.tables
where table_schema = 'public'
and table_name in (
    'sensor_minute_aggregates',
    'monitoring_incidents',
    'system_settings'
)
order by table_name;


-- Check the manager phone setting:
--
-- select key, value, updated_at
-- from public.system_settings
-- where key = 'manager_phone';


-- ============================================================
-- END OF LPMAS SUPABASE SETUP
-- ============================================================