-- ============================================================
-- LPMAS - GREENHOUSE CONFIGURATION (SUPABASE AS SOURCE OF TRUTH)
--
-- Tables:
--   1. greenhouses
--   2. greenhouse_sensors
--   3. greenhouse_recycle_bin
--
-- Greenhouse configuration (name, phase dates, monitoring window,
-- sensor assignments) now lives here, not only in the Raspberry
-- Pi's local SQLite. The Pi pulls this down and mirrors it locally
-- so its own per-reading classification logic keeps working without
-- a live round-trip on every 10-second sensor POST.
--
-- Writes never go through the anon/authenticated Supabase key
-- directly (matching this project's existing convention for
-- sensor_minute_aggregates/monitoring_incidents/system_settings —
-- see 0002_monitoring_data.sql). Instead, authenticated clients call
-- the security-definer RPC functions below, which check the
-- caller's role against profiles the same way log_activity() does.
-- ============================================================


-- ============================================================
-- 1. GREENHOUSES
-- ============================================================

create table if not exists public.greenhouses (
    id text primary key,
    name text not null,

    phase_start date not null,
    phase_end date not null,
    window_start time not null,
    window_end time not null,

    is_active boolean not null default true,

    updated_at timestamptz not null default now(),
    updated_by uuid references public.profiles(id),

    constraint greenhouses_phase_range_check
        check (phase_end >= phase_start)
);

create index if not exists idx_greenhouses_is_active
    on public.greenhouses (is_active);


-- ============================================================
-- 2. GREENHOUSE SENSORS
-- ============================================================
-- A real sensor is assigned to at most one greenhouse at a time,
-- matching the existing Pi-side rule in app.py.
-- ============================================================

create table if not exists public.greenhouse_sensors (
    greenhouse_id text not null references public.greenhouses(id) on delete cascade,
    sensor_id text not null,

    primary key (greenhouse_id, sensor_id),
    constraint greenhouse_sensors_sensor_unique unique (sensor_id)
);


-- ============================================================
-- 3. GREENHOUSE RECYCLE BIN
-- ============================================================
-- A snapshot of a greenhouse's configuration at the moment it was
-- deleted, so a manager/admin can see what used to exist. Restoring
-- from this table is not implemented yet — this is storage/listing
-- only for now.
-- ============================================================

create table if not exists public.greenhouse_recycle_bin (
    id bigint generated by default as identity primary key,

    greenhouse_id text not null,
    name text not null,
    config jsonb not null,

    deleted_at timestamptz not null default now(),
    deleted_by uuid references public.profiles(id)
);

create index if not exists idx_greenhouse_recycle_bin_deleted_at
    on public.greenhouse_recycle_bin (deleted_at desc);


-- ============================================================
-- 4. ROW LEVEL SECURITY
-- ============================================================

alter table public.greenhouses
    enable row level security;

alter table public.greenhouse_sensors
    enable row level security;

alter table public.greenhouse_recycle_bin
    enable row level security;


-- ------------------------------------------------------------
-- GREENHOUSES / GREENHOUSE_SENSORS
-- ------------------------------------------------------------
-- Unlike sensor_minute_aggregates/monitoring_incidents, these are
-- readable by anon too: the public, unauthenticated Monitor page
-- needs the greenhouse list and sensor assignments to render live
-- data, the same information that used to be baked into the
-- client bundle when it came straight from the Pi.
--
-- Direct client writes stay blocked either way — see the RPC
-- functions below for the only supported write path.
-- ------------------------------------------------------------

drop policy if exists "Anyone can view greenhouses" on public.greenhouses;
create policy "Anyone can view greenhouses"
on public.greenhouses
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users cannot write greenhouses directly" on public.greenhouses;
create policy "Authenticated users cannot write greenhouses directly"
on public.greenhouses
for all
to authenticated
using (false)
with check (false);

drop policy if exists "Anyone can view greenhouse sensors" on public.greenhouse_sensors;
create policy "Anyone can view greenhouse sensors"
on public.greenhouse_sensors
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users cannot write greenhouse sensors directly" on public.greenhouse_sensors;
create policy "Authenticated users cannot write greenhouse sensors directly"
on public.greenhouse_sensors
for all
to authenticated
using (false)
with check (false);


-- ------------------------------------------------------------
-- GREENHOUSE RECYCLE BIN
-- ------------------------------------------------------------
-- Not public: only signed-in users (in this app, that always
-- means admin or manager — there is no other authenticated role)
-- can see what has been deleted. Direct writes are blocked the
-- same way; only delete_greenhouse() below can insert here.
-- ------------------------------------------------------------

drop policy if exists "Authenticated users can view the recycle bin" on public.greenhouse_recycle_bin;
create policy "Authenticated users can view the recycle bin"
on public.greenhouse_recycle_bin
for select
to authenticated
using (true);

drop policy if exists "Authenticated users cannot write the recycle bin directly" on public.greenhouse_recycle_bin;
create policy "Authenticated users cannot write the recycle bin directly"
on public.greenhouse_recycle_bin
for all
to authenticated
using (false)
with check (false);


-- ============================================================
-- 5. EXPLICIT POSTGREST GRANTS
-- ============================================================
-- Existing tables in this project rely on Supabase's default
-- grants from when the project was first created. Supabase is
-- rolling out a requirement for explicit grants on new tables for
-- PostgREST access (existing free projects affected from
-- 2026-10-30), so these are added up front rather than relying on
-- a default that may not apply to tables created after that date.
-- RLS above still governs actual row access either way.
-- ============================================================

grant select on public.greenhouses to anon, authenticated;
grant select on public.greenhouse_sensors to anon, authenticated;
grant select on public.greenhouse_recycle_bin to authenticated;

-- Table-level grants only need to cover what the RPC functions
-- below actually do as security definer; direct client
-- insert/update/delete stays blocked by the RLS policies above
-- regardless of these grants.
grant insert, update, delete on public.greenhouses to authenticated;
grant insert, delete on public.greenhouse_sensors to authenticated;
grant insert on public.greenhouse_recycle_bin to authenticated;


-- ============================================================
-- 6. WRITE FUNCTIONS (SECURITY DEFINER, MATCHING log_activity())
-- ============================================================
-- Both functions check the caller's role via profiles, the same
-- way log_activity() already does in 0004_finalize_activity_logs.sql,
-- rather than trusting anything the client sends.
-- ============================================================

create or replace function public.upsert_greenhouse(
    p_id text,
    p_name text,
    p_sensor_ids text[],
    p_phase_start date,
    p_phase_end date,
    p_window_start time,
    p_window_end time
)
returns public.greenhouses
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text;
    v_result public.greenhouses;
begin
    select p.role::text into v_role from public.profiles p where p.id = auth.uid();

    if v_role is null or v_role not in ('admin', 'manager') then
        raise exception 'Not authorized to manage greenhouses';
    end if;

    if p_id is null or length(trim(p_id)) = 0 then
        raise exception 'Greenhouse id is required';
    end if;

    if p_name is null or length(trim(p_name)) = 0 then
        raise exception 'Greenhouse name is required';
    end if;

    if p_sensor_ids is null or array_length(p_sensor_ids, 1) is null then
        raise exception 'At least one sensor is required';
    end if;

    insert into public.greenhouses (
        id, name, phase_start, phase_end, window_start, window_end, is_active, updated_at, updated_by
    )
    values (
        p_id, p_name, p_phase_start, p_phase_end, p_window_start, p_window_end, true, now(), auth.uid()
    )
    on conflict (id) do update set
        name = excluded.name,
        phase_start = excluded.phase_start,
        phase_end = excluded.phase_end,
        window_start = excluded.window_start,
        window_end = excluded.window_end,
        is_active = true,
        updated_at = now(),
        updated_by = auth.uid()
    returning * into v_result;

    -- A sensor belongs to at most one greenhouse at a time.
    delete from public.greenhouse_sensors
    where sensor_id = any(p_sensor_ids) and greenhouse_id != p_id;

    delete from public.greenhouse_sensors where greenhouse_id = p_id;

    insert into public.greenhouse_sensors (greenhouse_id, sensor_id)
    select p_id, s from unnest(p_sensor_ids) as s;

    return v_result;
end;
$$;

grant execute on function public.upsert_greenhouse(text, text, text[], date, date, time, time) to authenticated;


create or replace function public.delete_greenhouse(p_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text;
    v_row public.greenhouses;
    v_sensor_ids text[];
begin
    select p.role::text into v_role from public.profiles p where p.id = auth.uid();

    if v_role is null or v_role not in ('admin', 'manager') then
        raise exception 'Not authorized to manage greenhouses';
    end if;

    select * into v_row from public.greenhouses where id = p_id;

    if not found then
        raise exception 'Greenhouse not found';
    end if;

    select coalesce(array_agg(sensor_id), '{}') into v_sensor_ids
    from public.greenhouse_sensors where greenhouse_id = p_id;

    insert into public.greenhouse_recycle_bin (greenhouse_id, name, config, deleted_by)
    values (
        v_row.id,
        v_row.name,
        jsonb_build_object(
            'phase_start', v_row.phase_start,
            'phase_end', v_row.phase_end,
            'window_start', v_row.window_start,
            'window_end', v_row.window_end,
            'sensor_ids', to_jsonb(v_sensor_ids)
        ),
        auth.uid()
    );

    delete from public.greenhouse_sensors where greenhouse_id = p_id;
    delete from public.greenhouses where id = p_id;
end;
$$;

grant execute on function public.delete_greenhouse(text) to authenticated;
